/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f103xx.h>
#include "stm32f103xx_gpio.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(uint32_t time);

int main(void)
{
	/*GPIO Init for LED blinking*/
	GPIO_Output_Init(GPIOA, GPIO_PIN_10, GPIO_OUTPUT_MODE_2MHZ, GPIO_OUT_GP_PUSH_PULL);
	/*GPIO Init for button*/
	GPIO_Input_Init(GPIOA, GPIO_PIN_0, GPIO_IN_LOGIC, GPIO_PULL_DOWN);

	while(1){
		/*Check if pin reading is '1'*/
		if(GPIO_ReadPin(GPIOA,GPIO_PIN_0)==1){
			GPIO_WritePin(GPIOA,GPIO_PIN_10,SET); /*Sets to 3.3V pin A10 while pushing BTN with pull down resistor*/
		}else{
			/*Pin reading is '0'*/
			GPIO_WritePin(GPIOA,GPIO_PIN_10,RESET); /*Sets to 0V pin A10 while pushing BTN with pull down resistor*/
		}
		/*Notice that  push-pull is required if you will measure pin A10 without a pull-up or down external resistor
		 * if you initialized pin A10 in open-drain. It is not necessary if it is in push-pull config*/
		/*Warning: if you are connecting BTN with pull-down resistor, don't care if pin A0 is gpio pull_down either
		 * gpio pull-up configuration, due to external resistor is taking control of electronic circuit.
		 * If you take off external reisistor and just leave the button (A0-BTN-GND) you will notice that
		 * internal resistor will take control of the electronic circuit and pull-up or pull-down config
		 * will make sense at the firmware logic*/
	}
}
